language: node_js
node_js:
  - "10.0"
  - "11.0"
before_install:
  - sudo apt-get update
  - sudo apt-get install clamav clamav-daemon clamav-freshclam
  - sudo freshclam -v
  - sudo service clamav-daemon restart
